# Generated by Django 2.2.3 on 2020-04-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_store', '0013_auto_20200331_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='sale.jpg', upload_to=''),
        ),
    ]
