# Generated by Django 2.2.3 on 2020-04-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_store', '0014_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.URLField(default='sale.jpg'),
        ),
    ]
