# Generated by Django 2.2.3 on 2020-04-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_store', '0015_auto_20200401_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FilePathField(default='sale.jpg'),
        ),
    ]
