# Generated by Django 2.2.3 on 2020-04-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_store', '0016_auto_20200401_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(default='sale.jpg', max_length=400),
        ),
    ]
