# Generated by Django 2.2.3 on 2020-04-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_store', '0017_auto_20200401_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='sale.jpg', max_length=400, upload_to=''),
        ),
    ]
