# Generated by Django 2.2.3 on 2020-04-01 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_store', '0019_auto_20200401_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_store.PhoneCat'),
        ),
    ]
