# Generated by Django 2.2.3 on 2020-04-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_store', '0020_auto_20200401_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('AP', 'Apple'), ('AN', 'Android')], default='AP', max_length=2),
        ),
    ]
