# Generated by Django 2.2.3 on 2020-04-01 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_store', '0023_auto_20200401_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
