# Generated by Django 2.2.3 on 2020-04-03 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_store', '0029_auto_20200403_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='title',
            new_name='phone_name',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='phone',
        ),
    ]
